name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  BuildDesktop:
    name: ${{ matrix.name }}
    permissions: write-all
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-2022
            buildArgs: windows
            exportPath: windows
            artifactName: lumen.windows
            setupScript: .\"setup/windows.bat"
            artifactPath: export\release\windows\bin\*
          - name: Linux
            os: ubuntu-22.04
            buildArgs: linux
            exportPath: linux
            setupScript: sh ./setup/unix.sh
            artifactName: lumen.linux
            artifactPath: export/release/linux/bin/*
          # - name: macOS x86_64
          #   os: macos-14
          #   buildArgs: "mac -64 -D HXCPP_M64"
          #   exportPath: macos
          #   setupScript: sh ./setup/mobile.sh
          #   artifactName: P-Slice.1.0.macosx64
          #   artifactPath: export/release/macos/bin/*
          - name: macOS AArch64
            os: macos-15
            buildArgs: mac
            exportPath: macos
            setupScript: sh ./setup/mobile.sh
            artifactName: lumen.macos-arm64
            artifactPath: export/release/macos/bin/*
    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      setupScript: ${{ matrix.setupScript }}
      exportPath: ${{ matrix.exportPath }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}